### ISSUE TITLE
relative jump offsets do not accept decimal values

### ISSUE THREAD

**Issue by nww02** [Dotneteer/spectnetide#143]
I get:

"Error Z0022: Relative jump distance should be between -128 and 127. [xxxxxx] is invalid"
where [xxxxxx] is a strange number that doesn't seem to be related to the number passed in.
when attempting to do a relative djnz or jr as:

djnz 1
or (for example)
jr  nc,1

I cannot seem to use hex values for these with "#" or "h".
Attempting to prepend with a "$" kind-of works, but only if you also add a "+" or "-", e.g.

jr nc,$+1

Many thanks

**Comment by Dotneteer** [comment]
@nww02, the `djnz` and `jr` instructions work this way by design. The value you specify is considered as the absolute target address and the compiler calculates the length of the relative jump. When it does not fit the -127...128 range, it gives you an error message. The strange number is the distance of the current and the target addresses.

The only way (also by design) is the specify the target relatively using the current address operator (`$`, `.`, or `*`, all tokens are accepted), such as `$+1`, `*-2`, etc.

If you have any suggestion for a relative jump syntax that does not break the existing construct, I'm open to implementing it.

**Comment by nww02** [comment]
I've been looking into it since last night... I think I understand it better now... I'm used to the relative jumps on other compilers.  As the jr uses a relative offset, I expected that "$-x" would be an absolute address (since $ is 'here'), so was expecting "jr -1" to be the syntax.  

I didn't realise the compiler was doing clever stuff in the background :).  Also, I was bamboozled by the way that the jump offset always seemed to be wrong by two bytes too, but I've since learned this is also a long-standing 'feature' which veterans know to account for. :)   

If you don't believe there's an actual issue, I'm happy to close this, due to my lack of understanding of the "$" syntax.
