### ISSUE TITLE
Emulator screen not properly updated when debugging

### ISSUE THREAD

**Issue by Ultrahead** [Dotneteer/spectnetide#149]
SpectNetIde: 1.19.2
Visual Studio: 16.1.3

The screen does not properly update when debugging as can be seen in the following screenshot:

![image](https://user-images.githubusercontent.com/12087040/59419778-f7505980-8da1-11e9-83c3-3ddc6864e0a1.png)

That is for a 48k project and it remains the same throughout the whole loop until you reach the end of it (then, the message is properly displayed).

Also, if you remove the breakpoint and hit F5 (or press the start debugging icon), it will pause there (as if the breakpoint were never removed)

![image](https://user-images.githubusercontent.com/12087040/59419984-6fb71a80-8da2-11e9-8286-d85688d5c5d0.png)

**Comment by Dotneteer** [comment]
@Ultrahead, You mention two issue in this ticket. The second one (you remove the breakpoint, but the code execution still stops) is a bug, and I will fix it soon.

Nonetheless, the first phenomenon is normal :-). Here is a short explanation:

When you pause the code, not only the CPU but the ULA is paused in the virtual machine, and the display shows the current screen frame being rendered. If you write something into the screen memory, that content will be visible only when the virtual electron beam of the screen renders the content on the screen. Because the ULA (in PAL mode) renders the screen in every 1/50th second, it might happen that you see the effect of a pixel set/reset only 1/50th second later. The pause command pauses the virtual electron beam, too.

So, in your case, the character the code wrote on the screen is already in the screen memory, but the virtual electron beam has not reached that position yet. If you take a closer look at the screenshot you've sent me, you can see that the virtual electron beam is stopped in the row that has white pixels to the left and black pixels at the right (somewhere in the middle of the screen). If instead of continueing the program from the paused position you use the step-into command to execute Z80 instructions one-by-one, you can see what the ULA does while the CPU carries out a single operation.

I hope, my explanation was clear enough...

**Comment by Dotneteer** [comment]
Fixed. Released in v1.19.3.

**Comment by Ultrahead** [comment]
Hi, thanks for the explanation. And yes, it is clear enough.

Is there any chance that in debug mode, when a breakpoint gets, the virtual electron beam gets paused after a period of time? To give enough time for a screen refresh. That would be very handy as a complement for the step-into command.

________________________________
De: Istvan Novak <notifications@github.com>
Enviado: Thursday, June 13, 2019 9:30:12 AM
Para: Dotneteer/spectnetide
Cc: Pedro Güida; Mention
Asunto: Re: [Dotneteer/spectnetide] Emulator screen not properly updated when debugging (#149)


@Ultrahead<https://github.com/Ultrahead>, You mention two issue in this ticket. The second one (you remove the breakpoint, but the code execution still stops) is a bug, and I will fix it soon.

Nonetheless, the first phenomenon is normal :-). Here is a short explanation:

When you pause the code, not only the CPU but the ULA is paused in the virtual machine, and the display shows the current screen frame being rendered. If you write something into the screen memory, that content will be visible only when the virtual electron beam of the screen renders the content on the screen. Because the ULA (in PAL mode) renders the screen in every 1/50th second, it might happen that you see the effect of a pixel set/reset only 1/50th second later. The pause command pauses the virtual electron beam, too.

So, in your case, the character the code wrote on the screen is already in the screen memory, but the virtual electron beam has not reached that position yet. If you take a closer look at the screenshot you've sent me, you can see that the virtual electron beam is stopped in the row that has white pixels to the left and black pixels at the right (somewhere in the middle of the screen). If instead of continueing the program from the paused position you use the step-into command to execute Z80 instructions one-by-one, you can see what the ULA does while the CPU carries out a single operation.

I hope, my explanation was clear enough...

**Comment by Dotneteer** [comment]
Pedro, It is not very clear what would you like to achieve with "the virtual electron beam gets paused after a period of time". Probably, you think that it would be great to see what is on the screen, even it is not entirely rendered?

**Comment by Ultrahead** [comment]
Yes, that is what I tried to mean.

On Jun 14, 2019 1:37 AM, Istvan Novak <notifications@github.com> wrote:

Pedro, It is not very clear what would you like to achieve with "the virtual electron beam gets paused after a period of time". Probably, you think that it would be great to see what is on the screen, even it is not entirely rendered?

**Comment by Dotneteer** [comment]
Pedro, I opened a new issue, #150 to handle your request. If you have any comments or suggestion related to the screen rendering topic, please add them to the new issue.

**Comment by Ultrahead** [comment]
Great! Thanks!
