### ISSUE TITLE
Exception starting emulator

### ISSUE THREAD

**Issue by garethadams** [Dotneteer/spectnetide#156]
I'm running Visual Studio 2019 16.3.1. I've installed SpectNetIDE and created a ZX Spectrum Code Discovery Project.

The ZX Spectrum IDE menu appears under Extensions rather than as a top level menu which is contrary to the documentation.

When I select ZX Spectrum Emulator I get the following error:

"Exception has been thrown by a target of an invocation"

**Comment by Dotneteer** [comment]
@garethadams, thanks for signing me this issue!

Though in the VS 2017 version, SpectNetIDE has a top-level ZX Spectrum IDE menu, it is not possible in VS 2019, as the IDE automatically moves top-level menus under Extensions.

_The bad news:_

By my experience the "Exception has been thrown by a target of an invocation" message appears when you cold-start VS 2019 and select an existing solution. This behavior is due to an architectural change in VS 2019 (from VS 2017) that causes the solution being loaded before loading SpectNetIDE, and not notifying the IDE when the entire solution load has been completed.

There's a workaround: close the solution, and open it again. I know, it is annoying, but right now, this is the only available resolution. I cannot issue a simple fix, as I need to change the underlying architecture significantly.

_The good news:_

I'm actively working on SpectNetIDE v2.0 (for VS 2019). I have a very good progress, in a few weeks I will release the first preview. This version handles solution load in a totally different -- VS 2019 compatible -- way. v2.0 won't support VS 2017, as I intend to focus my limited time to a single version. (You can find the source code in the `v2` branch within the `v2` folder)

Soon I will announce the main features publicly. Here are a few things:

- VS integration architecture redesigned from scratch
- Multiple ZX Spectrum projects in a solution
- New debugging features (shadow screen rendering, ULA raster position indication)
- Better syntax highlighting through Visual Studio Language Services
- Boriel's BASIC integration (will be released in 2.x, but definitely not in v2.0)

Though I cannot solve the issue immediately, hopefully, you'll like the new version.

**Comment by garethadams** [comment]
@Dotneteer - thanks for the quick reply. You're right, closing the solution and re-opening worked.

Look forward to v2

Cheers
