### ISSUE TITLE
[v2p2] importing zxbas project does not run

### ISSUE THREAD

**Issue by Ultrahead** [Dotneteer/spectnetide#167]
After importing this project to SpectNetIDE 2 preview (changing all the files from .bas to .zxbas and ditto in code):

http://www.alessandrogrussu.it/Adlunam.html

... nothing happens when you compile and run the game (ad10.zxbas file)

**Comment by Dotneteer** [comment]
Hi @Ultrahead, I will check it soon.

**Comment by Dotneteer** [comment]
@Ultrahead, thanks for reporting this error. The AdLunam project is a very good one to test ZX BASIC integration, as it is complex, and using many ZX BASIC features. I identified a number of issues (probably just the surface) that I need to handle in SpectNetIDE:
- The ZX BASIC integration had bugs with command line option handling
- I need to find a way to specify ZXB command line options within the main `.zxbas` file so that options could be passed to ZXB.EXE (using the default options that you can set for SpectNetIDE is not enough)
- Compiling AdLunam from ZX BASIC to assembly takes more than two minutes, so I need to provide some visual feedback to the user
- The SpectNetIDE assembly does not recognize the `INCBIN` pragma (it uses `INCLUDEBIN`).
- etc.

I try to process this long feature queue still this year...

**Comment by Dotneteer** [comment]
I managed to run the AdLunam project within SpectNetIDE. I will carry out the necessary changes and release them in Preview 4.

**Comment by Dotneteer** [comment]
@Ultrahead, the fix for the AdLunam project released in Preview 4. 

A new SpectNetIDE feature allows you to add command line options to the main file of a ZX BASIC program. Accordingly, to make AdLunam work, you should add this top comment to the `ad10.zxbas` file:

```
REM @options --array-base=1 --string-base=1 -O3 -H 2100 -S 24600
```

You can find more details about compilation options here: https://dotneteer.github.io/spectnetide/getting-started/use-zx-basic#option-comments

Please note, the compilation takes about 2 minutes by the ZXB compiler. Then, SpectNetIDE adds about two seconds to compile the output `.z80asm` file to machine code.

**Comment by Ultrahead** [comment]
Great! Works like a charm ...
