### ISSUE TITLE
Injecting Code changes the text entry mode

### ISSUE THREAD

**Issue by nww02** [Dotneteer/spectnetide#175]
If I am at the BASIC Prompt with the [K]  cursor flashing after boot, I can press "T" to get the word RANDOMIZE (as you would expect).  However If instead of pressing T, I inject my program first:-

PAUSE  the emulator
INJECT my code at #8000
UNPAUSE the emulator

the [K] cursor is still flashing  Now I press T but instead of getting "RANDOMIZE", I get "t", as if the cursor was in "L" mode, yet it was still flashing in "K" mode!

Pressing DELETE to get rid of the "t" will return the cursor to "K" mode, and then I can press "T" to get RANDOMIZE again, as normal.   Makes me wonder if any other things change by injecting code?

Version: 2.0.6

**Comment by Dotneteer** [comment]
@nww02 , injecting the code explicitly sets the cursor to [L], just as if you'd start the code with RUN. However, as your example shows, in certain cases it would be better to leave it in [K] mode.
To resolve this issue, I'd add a pragma to SpectNetIDE assebler so that your code can specify the cursor mode to use when injecting the code.
Any other ideas?

**Comment by nww02** [comment]
I don't know what happens in the background.. I think when just injecting, the cursor should be left alone.   Sure if you use the full RUN option it could be set to L... If you're just injecting, you're probably still in BASIC mode and running snippets to test them :)

**Comment by Dotneteer** [comment]
Fixed, will be released in Preview 6.

**Comment by nww02** [comment]
Cool! :)

**Comment by Dotneteer** [comment]
Released in v2 Preview 6.
