### ISSUE TITLE
Exception on the output tab when VS 2019 is open

### ISSUE THREAD

**Issue by gusmanb** [Dotneteer/spectnetide#183]
Whenever I open a project (even without being a spectrum one) VS gets stuck some seconds and then I can see this:

```
Exception occured in SpectNetIde: Referencia a objeto no establecida como instancia de un objeto.
Full message: $System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en Spect.Net.VsPackage.Commands.CreateVfddFileCommand.OnQueryStatus(OleMenuCommand mc) en C:\Users\dotne\source\repos\spectnetide\v2\VsIntegration\Spect.Net.VsPackage\Commands\CreateVfddFileCommand.cs:línea 33
   en Spect.Net.VsPackage.VsxLibrary.Command.SpectNetCommandBase.<.ctor>b__23_1(Object s, EventArgs e) en C:\Users\dotne\source\repos\spectnetide\v2\VsIntegration\Spect.Net.VsPackage\VsxLibrary\Command\SpectNetCommandBase.cs:línea 87
Exception occured in SpectNetIde: Referencia a objeto no establecida como instancia de un objeto.
Full message: $System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en Spect.Net.VsPackage.Commands.CreateVfddFileCommand.OnQueryStatus(OleMenuCommand mc) en C:\Users\dotne\source\repos\spectnetide\v2\VsIntegration\Spect.Net.VsPackage\Commands\CreateVfddFileCommand.cs:línea 33
   en Spect.Net.VsPackage.VsxLibrary.Command.SpectNetCommandBase.<.ctor>b__23_1(Object s, EventArgs e) en C:\Users\dotne\source\repos\spectnetide\v2\VsIntegration\Spect.Net.VsPackage\VsxLibrary\Command\SpectNetCommandBase.cs:línea 87
```

I think it has started happening when I updated VS to version 16.5.1

**Comment by Dotneteer** [comment]
Thanks, I will examine this issue soon.

**Comment by Dotneteer** [comment]
@gusmanb , After trying for several hours and on different machines, I did not manage to reproduce this error. Nonetheless, as I see, you have Spanish Visual Studio 2019/.NET installed on your machine.
According to the source code I see that the particular error message is displayed because the SpectNetIDE Visual Studio Package may not have been properly intialized. Can you help me with some more details? Do you see anything in ActivityLog.xml?
I know, it's not a very scientific answer, but in many cases, I could fix such issues by reinstalling/repairing VS 2019.

**Comment by gusmanb** [comment]
VS got updated to 15.6.2 right now and I get no more the exception... so it should be a VS 15.6.1 bug. If I get again the exception message I will enable the log and attach it.

Cheers :)

**Comment by Dotneteer** [comment]
It's annoying how many times such issues happen with many new VS releases. Nonetheless, I'm happy that this issue got away with 15.6.2 :-)
