### ISSUE TITLE
Disp pragma and Relative jump

### ISSUE THREAD

**Issue by neicv** [Dotneteer/spectnetide#196]
.disp pragma not working as expected.

1.  
Some block:
.org #8000
.disp #1000
Some CODE

- Work wrong, 
![disp1](https://user-images.githubusercontent.com/18497721/82079337-5f629a80-96eb-11ea-8cbf-c9b6e5c58e59.JPG)

2.
Some block:
.org #8000
Some CODE
.disp #1000

- Work right
![disp2](https://user-images.githubusercontent.com/18497721/82079369-6e494d00-96eb-11ea-9afb-7c2c16fe88a8.JPG)

But anyway:
Disp pragma and Relative jump not work correctly.
Error Z0022: Relative jump distance should be between -128 and 127. -65500 

![disp3](https://user-images.githubusercontent.com/18497721/82079403-7acda580-96eb-11ea-8e82-397a187520cc.JPG)

**Comment by Dotneteer** [comment]
@neicv, Thanks for signing this issue! I will investigate it soon :-)

**Comment by Dotneteer** [comment]
Evgeny, thanks again for submitting these issues. I managed to find and fix them. Here I send you a private build so that you can test them. Please, rename the `.vsix` file to `.zip`.

[Spect.Net.VsPackage.zip](https://github.com/Dotneteer/spectnetide/files/4638437/Spect.Net.VsPackage.zip)

Please, let me know how the fix works! Of course, if you find other bugs, or just have questions about SpectNetIDE, feel free to nofify me.

I plan to release these fixes in Preview 9.

Here is the summary about the fix:

**Issue 1: the `.disp` pragma**

The compiler works exactly as described in the specification. However, the **Run program**, **Debug program**, and **Inject code** commands filled the code into a wrong address.

According to the compiler specification the [ORG pragma](https://dotneteer.github.io/spectnetide/documents/pragmas#the-org-pragma) defines the address to place the code. Even if you set the [DISP pragma](https://dotneteer.github.io/spectnetide/documents/pragmas#the-disp-pragma), the code is to be loaded into the segment specified by ORG. The DISP pragma defines a displacement for the code address translation. It assumes that you use the displacement to move the code in the memory during runtime.

However, the code injector was faulty: it injected the code to the ORG+DISP address (as your screenshots indicated).

Here are the screenshoots that show the fixed state.

The original state without DISP compiles and injects as you expect:

![devenv_8Osls831NS](https://user-images.githubusercontent.com/4783390/82121195-70fb7f00-978b-11ea-8388-aae3334161e2.png)

When you add the DISP pragma right after the `ORG #8040`, from that point, all addresses are displaced with `-#0020` bytes:

![devenv_AHTSXTkBTA](https://user-images.githubusercontent.com/4783390/82121233-c172dc80-978b-11ea-92a0-91cd3d9ba0ba.png)

When you place the `.disp -#0020` pragma to the end of the code, it starts address displacement from that point on &mdash; however, you have no more code, so it has no effect:

![devenv_KmOeB9thCi](https://user-images.githubusercontent.com/4783390/82121304-43fb9c00-978c-11ea-9563-3aa3a9369311.png)


**Issue 2: the `jr` statement**:

There was an issue in the compiler that made a wrong (signed) conversion of a displacement instead of an unsigned conversion. Now, it works properly.

**Comment by neicv** [comment]
thx for answer! 
After fix:
disp work fine!

But "jr" - not 
(before disp??)

![jr2](https://user-images.githubusercontent.com/18497721/82127073-a8812000-97b9-11ea-89c7-20d1b252f13c.PNG)

**Comment by Dotneteer** [comment]
Evegeny, you're right. Let me fix this error!

**Comment by Dotneteer** [comment]
Evgeny, here is the fix for the JR + DISP issue:

[Spect.Net.VsPackage.zip](https://github.com/Dotneteer/spectnetide/files/4639692/Spect.Net.VsPackage.zip)

**Comment by neicv** [comment]
Hellou Istvan!
Now work correctly
 thanks for fix it!

And thank you very much for your work!

**Comment by Dotneteer** [comment]
Evgeny, this is the strength of the community :-). Many issues and bugs in SpectNetIDE were fixed with the help of community members eager like you!

If you're happy with SpectNetIDE, please, star the project on Github.

I will close this issue when Preview 9 is released.

**Comment by Dotneteer** [comment]
Released in v2 Preview 9.
