### ISSUE TITLE
Spectrum output screen is distorted when having a custom scale setting in Windows

### ISSUE THREAD

**Issue by oxidaan** [Dotneteer/spectnetide#204]
Hello,
I am using a 125% scaling in Windows (Settings->Display->Scale and layout->'Change the size of text, apps, and other items').
This causes the spectrum output screen to be (slightly) distorted, it doesn't handle this dpi zooming properly.
(I really need this 125% zooming - I guess most of your audience has reached a 'reading glasses' age...)
Other spectrum simulators don't have this problem btw.
To reproduce, adjust scaling as desrcibed and check spectrum output window.

**Comment by Dotneteer** [comment]
Fixed, will be released in the next preview.

**Comment by Dotneteer** [comment]
Sorry for ignoring your request for a such a long time. I had hard weeks behind me because of COVID. I still do not know when I will have time to release the next preview. However, her I send you a private build with the fix. Please, rename the `.zip` file to `.vsix` before installing it!

[Spect.Net.VsPackage.zip](https://github.com/Dotneteer/spectnetide/files/5695754/Spect.Net.VsPackage.zip)
