### ISSUE TITLE
Labels with dots in ASM break zx basic compilation

### ISSUE THREAD

**Issue by gusmanb** [Dotneteer/spectnetide#205]
After updating to version 1.13.1 of ZX Basic Spectnetide isn't able to compile the resulting assembler, two labels with dots break it.

The offending lines:

```
ZXBASIC_USER_DATA_LEN EQU ZXBASIC_USER_DATA_END - ZXBASIC_USER_DATA
	.__LABEL__.ZXBASIC_USER_DATA_LEN EQU ZXBASIC_USER_DATA_LEN
	.__LABEL__.ZXBASIC_USER_DATA EQU ZXBASIC_USER_DATA

```

Reported error: Z0100: Unexpected token: '.'

**Comment by Dotneteer** [comment]
Fixed, will be released in the next preview.

**Comment by Dotneteer** [comment]
As I do not know when I will be able to release the next preview, here I send you a private build with the fix. Observe, SpectNetIDE now uses the ZXBC.EXE instead of ZXB.EXE. (Rename the `.zip` to `.vsix` before installing it!)

[Spect.Net.VsPackage.zip](https://github.com/Dotneteer/spectnetide/files/5695764/Spect.Net.VsPackage.zip)

**Comment by chrisfoulds** [comment]
also hitting this, however I can't run that (after renaming) - is it just a 32-bit build ?

**Comment by gusmanb** [comment]
Tested, works perfectly.

Closing the issue.
