### ISSUE TITLE
Visibilty of buttons in emulator is not always correct

### ISSUE THREAD

**Issue by stuurmn** [Dotneteer/spectnetide#22]
Step 1) Run program in Emulator

![2017-11-07 17_09_55-as11](https://user-images.githubusercontent.com/33286419/32504134-687e643c-c3df-11e7-90ac-b224732e8b18.jpg)

Step 2)  Restart (Same) Program again

![2017-11-07 17_10_21-spect net - microsoft visual studio](https://user-images.githubusercontent.com/33286419/32504324-cdd968ae-c3df-11e7-8770-0624a501d53a.jpg)

Step 3) The popup ask if the VM should be restarted --> Click Yes

![2017-11-07 17_21_02-as11](https://user-images.githubusercontent.com/33286419/32504476-2df90672-c3e0-11e7-9abd-b92c2d9cac39.jpg)

![2017-11-07 17_10_38-as11](https://user-images.githubusercontent.com/33286419/32504152-71931d2e-c3df-11e7-8c4b-49d432c7c671.jpg)

The start button is green. But it is already running.    You can click on it but nothing is happening
![2017-11-07 17_10_53-as11](https://user-images.githubusercontent.com/33286419/32504191-861d4b0c-c3df-11e7-97ee-d31341ebf76e.jpg)

But you cant stop or pause the emulator

![2017-11-07 17_11_08-as11](https://user-images.githubusercontent.com/33286419/32504215-8fd7c9e2-c3df-11e7-8650-56078cdbfa66.jpg)

**Comment by stuurmn** [comment]
I just noticed if you activate another window and go back the visibilty seems to be ok again

**Comment by Dotneteer** [comment]
I did manage to reproduce this issue. Unfortunately, it is related to som visual studio extensibility issue. Even when I set the state of buttons in the code, VS does not refresh them. I definitely need time to dig into this issue.

**Comment by Dotneteer** [comment]
I did find the cause of the issue and the solution as well :-) The status of the command button is evaluated before the command is executed. However, the "Run Z80 program" and "Debug Z80 program" commands are executed asynchronously, and so they change command button states asybchronously. The IDE does not refresh them unless it has a reason. Shifting the focus away and back is such a reason.
I solved the problem by explicitly invoking the `UpdateCommandUI(int)` method of `IVsUIShell`.
I also added a virtual `bool UpdateUiWhenComplete { get; }` propery with `true` default value to `VsxAsyncCommand` so that you can turn off this behavior.
Now, async commands work as expected.
