### ISSUE TITLE
Looks like first Breakpoint is skipped

### ISSUE THREAD

**Issue by stuurmn** [Dotneteer/spectnetide#35]
When I start the program in Debug mode. It doesn't seem to stop
It seems to stop at the 2nd breakpoint.

![debuggerspectnetide](https://user-images.githubusercontent.com/33286419/32793813-484f8ca8-c967-11e7-89e2-ba4e08d23862.jpg)
It stops at the nop and not at the first Call

Question,
Do you know why in the bottom of the screen it only says   "@ 1982 Sincl                  "?

**Comment by Dotneteer** [comment]
The Z80 CPU's execution cycle checks for breakpoinst _after_ completing an instructions. Thus, the first instruction is executed, the PC points to the next instruction &mdash; as a result, the breakpoint at the very first instruction is missed.

**Comment by Dotneteer** [comment]
The "(c) 1982 Sincl" seems to miss the end of the text &mdash; it is not a bug. The reason is pretty simple :-). When you check the screen memory, the pixels that represent the text are already there. However, the ULA, which is responsible for rendering the screen pixel-by-pixel is still dealing with the upper lines of the screen.
The CPU and the ULA work in concert. When you pause the Spectrum vm at a particular breakpoint, it also pauses the ULA. This is why you do not see the end of the text.
When you continue to run, you can see that the text is displayed.

The Z80 Registers window now displays four counters that tell the ULA state:
* __FCL__ shows the ULA clock within a frame (an ULA frame contains 69888 clock cycles, each rendering two adjacent pixels including the border, the display area, and some non-visible area, too).
* __FRM__ shows the number of screen frames displayed since the Spectrum vm has been started.
* __RAS__ indicates the index of raster line in the screen (the whole screen is built from 312 lines)
* __PIX__ Shows the current pixel operation &mdash; It's difficult to explain, I will give you a detailed explanation later in the documentation...
