### ISSUE TITLE
I have a problem with the emulator not displaying correctly.

### ISSUE THREAD

**Issue by castingflame** [Dotneteer/spectnetide#72]
![screenshot_43](https://user-images.githubusercontent.com/11066890/39425961-bb250eb0-4c75-11e8-9972-94bca3d3fd3a.png)

All I am doing is using RST $10 to print to the screen and using your 'Debug' | 'Step through' buttons on the emulator.

![screenshot_44](https://user-images.githubusercontent.com/11066890/39426150-9b305122-4c76-11e8-97f1-129d9be5cf1a.png)

Cheers

**Comment by Dotneteer** [comment]
Hi castingflame.

I suppose, you see these screens shots while the virtual machine is paused (as you debug your code). I do not know exactly what Z80 assembly code you run, but according to the way the ULA in ZX Spectrum creates the screen, it might be totally normal what you see.

When you pause the code, not only the CPU but the ULA is paused in the virtual machine, and the display shows the current screen frame being rendered. If you write something into the screen memory, that content will be visible only when the virtual electron beam of the screen renders the content on the screen. Because the ULA (in PAL mode) renders the screen in every 1/50th second, it might happen that you see the effect of a pixel set/reset only 1/50th second later. The pause command pauses the virtual electron beam, too.

The top pictures is caught probably while the screen is being scrolled, the bottom one during teh `RST $10` call.

If you send me the source code, I can explain you in details, what happens :-)

**Comment by Dotneteer** [comment]
:-)
