### ISSUE TITLE
Security issue detected

### ISSUE THREAD

**Issue by madskristensen** [Dotneteer/spectnetide#73]
We’ve detected some invalid paths in the Dotneteer.SpectNedIDE-1.10.0.vsix which is embedded in your VSIX. The problem appears to be here: https://github.com/Dotneteer/spectnetide/blob/master/VsIntegration/Spect.Net.CodeDiscover.ProjectType/Spect.Net.CodeDiscover.ProjectType.csproj#L146 and below.

We have made the extension private at the Marketplace. You can mark it public any time once it is fixed. Please reach out to me at madsk@microsoft.com if you have any questions.

Mads Kristensen
Visual Studio Extensibility

**Comment by madskristensen** [comment]
Files that install outside the root folder of the extension are not allowed.  Please ensure all files install to or under the root extension folder

**Comment by Dotneteer** [comment]
Thanks for warning me, @madskristensen :-) I'm just about returning from my holidays, and will fix this issue soon.

**Comment by Dotneteer** [comment]
Oh, fixing this issue was pretty easy :-). I simply forget some experimental settings in the TargetPath property of the custom project system files. I've removed them and made some small adjustments.
In a few minutes ago, I published the new version (1.10.1) and made it public.
@madskristensen: thanks again for reporting me this issue :-).
