### ISSUE TITLE
Support "Step Out" function in the debugger

### ISSUE THREAD

**Issue by p3365** [Dotneteer/spectnetide#90]
The debugger supports "Step Over" and "Step Into" function. If you step into a large function there's now way to step out of the function, in order to terminate the single stepping inside that function. It can take considerable time to single step through lines of assembler until you hit a RET instruction.

One way of achieving this at the moment is to set a breakpoint on the instruction after the original call and then running the program until that breakpoint is hit. This is time consuming and inconvenient for a user. Other debuggers, such as the Microsoft C# debugger, support a "Step Out" function.

The SpecNetIDE debugger should support a "Step Out" function to do this automatically,

**Comment by Dotneteer** [comment]
When I designed the debugger, I was thinking about such a feature. The question I could not solve elegantly was to decide where do you complete a procedure/function. There might be many ways.
* `RET` (even its conditional forms) is relatively easy, however, it still has challenges.
* Many functions terminate with a JP to somewhere outside, for example back to the MAIN execution cycle point -- well, it is rare in custom code.
* There are functions that put data intentionally on the stack. They pop the return address before and use an indirect jump to return. Several compilers used by the community (using C development) use this technique.

Because of these issues, I cut this feature.

Nonetheless, if you have suggestions, I'd be happy to start implementing this request :-)

**Comment by p3365** [comment]
I agree that it would be difficult to cover all situations.

In my use case, covering the **"CALL"** (step into) and **"RET"** (step out) scenarios would be perfect including all variants of RET). 

If the code does weird stuff (e.g. CALL, POP then JP) then this would simply run until the next RET. I can't see any way of detecting all of these special cases. 

However, you _could_ monitor the stack pointer and detect that user is returning to the original address? If the program POPs this address from the stack (rather than returning to it) then the "Step Out" function disabled.

**Comment by Dotneteer** [comment]
Implemented, will be released soon.

**Comment by Dotneteer** [comment]
Released in v1.14.0
