### ISSUE TITLE
[feature request]  F5 to compile + deploy

### ISSUE THREAD

**Issue by nww02** [Dotneteer/spectnetide#93]
I don't know if I'm missing it, but it seems that the only way to recompile and run is to use the mouse, which also pops up two dialogs, and needs a right-click at a specific point, and then moving the cursor onto the spectrum window to highlight.  It would be great if there were hot keys to do that, so I didn't have to keep reaching for the mouse and clicking away dialogs...

F5 to 
* compile
* deploy the code
* reboot the VM
* focus on the VM

That would be nice :)

also shift-F5 to
* stop the VM
* return to the code

would be great too :)

**Comment by Dotneteer** [comment]
See my comment in #94.

**Comment by Dotneteer** [comment]
As I described in #94, it is very complicated to make F5 or Shift+F5 work as you'd like. However, you can easily get rid of the complicated start :-).

This is how it will work when I release the fix:

* In __Tools|Options__ within the Spec.Net IDE, you find three options, "Confirm code injection", and "Confirm code start", and "Confirm machine restart" respectively. Set them False to get rid of confirmation messages (These switches were the part of the IDE since the beginning).
* You can use the combination of two shortcut keys to execute these commands:
  * __Run Z80 Program__: `Ctrl+M`, `Ctrl+R`
  * __Debug Z80 Program__: `Ctrl+M`, `R`
  * __Stop the virtual machine: `Ctrl+M`, `Ctrl+S`

**Comment by Dotneteer** [comment]
Implemented, will be released soon.

**Comment by nww02** [comment]
That's great! thank you :)

**Comment by Dotneteer** [comment]
Fixed, released in v1.13.1.
