### ISSUE TITLE
[bug]  Cancelling a New Project still creates the folder

### ISSUE THREAD

**Issue by nww02** [Dotneteer/spectnetide#97]
to recreate:

  Close any open solution, then select "File > New Project", and select the ZX Spectrum Code Discovery Project, enter a Name in the name box, but then click [Cancel] to abort the creation of the new solution/project.

  If you navigate to the folder, you should see that despite aborting the creation the folder has already been created and the template structure imposed on it.

This doesn't happen if you don't edit the Name or make the name blank.

**Comment by Dotneteer** [comment]
@nww02, the issue you mention happens when you click OK in the "File > New Project" dialog after selection the ZX Spectrum Code Discovery project type, and click Cancel in the Create a New ZX Spectrum Project dialog.

Right now, it is a VS 2017 feature/bug. The IDE immediately creates the project folder (before popping up the dialog for the ZX Spectrum machine type). When the user cancels project creation, it notifies the IDE about this event. Unfortunately, the IDE does not remove the empty project folder.

About a year ago I tried to remove the folder in the code (provided the user had clicked Cancel), but VS IDE kept a lock on the project folder, so the code could not remove it.

Nonetheless, I try to implement this fallback procedure again, as VS 2017 had a few new releases since that time... :-)

**Comment by nww02** [comment]
:)  Good stuff! :)  hehe

**Comment by Dotneteer** [comment]
Fixed, released in v1.13.1. If you find my project valuable, please star it on GitHub and/or leave a review at https://marketplace.visualstudio.com/items?itemName=Dotneteer.SpectNetIde.
