### ISSUE TITLE
Please nest z80 menu entries for solution explorer context menu

### ISSUE THREAD

**Issue by CZEMacLeod** [Dotneteer/spectnetide#98]
The 5 extra Z80 menu entries available in the context menu of the solution explorer make the menu very untidy, especially when not using the add-in.

Would it be possible to put these as a sub-menu under a Z80 menu entry or similar? It could be selected from the options for backwards compatibility.

**Comment by Dotneteer** [comment]
@CZEMacLeod, putting all Z80 entries into a sub-menu is pretty easy, so I could quickly fix it. Nonetheless, VS IDE has limitations on using run time options to change the menu structure. When you install an extension in VS IDE, it merges new menu functions into the original menus of VS _in installation time_. Of course, I try to provide maximal backwards compatibility.
To implement your request, I need to make some special workaround so that you can turn sub-menus on or off with options. This workaround means duplicating all commands and changing their visibility dynamically.
I queue your request, and try to find the time to implement it :-) .

**Comment by Dotneteer** [comment]
Reading again your request, I guess, the real issue is (this is what you mean "untidy") that the ZX Spectrum-related functions should not be displayed in Solution Explorer when a different kind of project is loaded.
Well, it is a bug, so I will fix it. I won't create a sub-menu for these command, so you will see them as they are right now, but only for ZX Spectrum projects. __In other projects, you won't see these items in the Solution Explorer context menu at all.__

**Comment by Dotneteer** [comment]
Fixed, will be released soon.

**Comment by Dotneteer** [comment]
Fixed, released in v1.13.1. If you find my project valuable, please star it on GitHub and/or leave a review at https://marketplace.visualstudio.com/items?itemName=Dotneteer.SpectNetIde.
